name: LinuxSnap

on:
  workflow_dispatch

jobs:
  linux_build_snap:
    name: Build MeshLab (Linux - Snap)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y snapcraft
    - name: Setup env variables
      id: envs
      run: |
        echo "date=$(cat ML_VERSION)" >> $GITHUB_OUTPUT
    - name: Build MeshLab Snap
      run: |
        snapcraft
    - name: Rename Snap
      run: |
        mv ./meshlab*.snap ./MeshLab${{steps.envs.outputs.date}}-linux.snap
    - name: Upload Meshlab Snap
      uses: actions/upload-artifact@v4
      with:
        name: meshlab_linux_snap
        path: MeshLab${{steps.envs.outputs.date}}-linux.snap
